### ISSUE TITLE
After updating the headings' hashtags no longer have colors

### ISSUE THREAD

**Issue by IamSmeagol** [insanum/obsidian_nord#44] opened 2022-10-13 22:00 UTC
While on 0.15.* the hashtags had color to match the rest of the heading. If this change was intentional, could someone point me in the right direction to modify it on my vault?

**Comment by Smeagol2069** [comment] 2022-10-14 13:23
I also noticed that linked pages are orange even if they are part of a heading that should be a different color. I think that this is not the same behavior as previous versions.

**Comment by insanum** [comment] 2022-10-14 16:51
You have two issues posted here:
1. Hashtags in the live editor are white and the header text is a different color (based on level).
2. Links in a header are the same color as the header itself so they aren't noticable.

Ok... answers:
1. This is now the behavior of the default theme. I kept that way as I think it's a nice look. Also this is only visible when your cursor is on that line.
2. This one is a tad more difficult. The problem is this only occurs in level 2 & 6 headings since the those header color uses the same color as that defined for links.

I'm not going to change the behavior of the first issue as I don't think it's an issue.

The second one requires more thought. I'll address this soon.

**Comment by Smeagol2069** [comment] 2022-10-14 17:09
Sorry, I thought they were related and didn't want to create too many issues.


Thank you for this theme and your time!

**Comment by insanum** [comment] 2022-10-15 01:10
Will be fixed in the next update. I ended up removing the link color as a color used for heading. This results in always seeing a link in a header.

**Closed as completed by insanum** 2022-10-15 01:10 UTC
